// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function GetDefaultSaveDir() {
  return window['go']['main']['App']['GetDefaultSaveDir']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Receive(arg1, arg2) {
  return window['go']['main']['App']['Receive'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
