// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer():Promise<void>;

export function GetDefaultSaveDir():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function Receive(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function Send(arg1:string):Promise<string>;
